INSERT INTO DEPARTMENT (ID, NAME, MANDATORY, READ_ONLY)
VALUES (NEXTVAL('SEQ_DEPARTMENT_ID'), 'Organisation', TRUE, TRUE);

INSERT INTO DEPARTMENT (ID, NAME, MANDATORY, READ_ONLY)
VALUES (NEXTVAL('SEQ_DEPARTMENT_ID'), 'Finance', FALSE, FALSE);

INSERT INTO DEPARTMENT (ID, NAME, MANDATORY, READ_ONLY)
VALUES (NEXTVAL('SEQ_DEPARTMENT_ID'), 'Peoples', FALSE, FALSE);

INSERT INTO DEPARTMENT (ID, NAME, MANDATORY, READ_ONLY)
VALUES (NEXTVAL('SEQ_DEPARTMENT_ID'), 'Development', FALSE, FALSE);