INSERT INTO DEPARTMENT (ID, NAME, MANDATORY, READ_ONLY)
VALUES (NEXTVAL('SEQ_DEPARTMENT_ID'), 'Organisation', TRUE, TRUE);

INSERT INTO DEPARTMENT (ID, NAME, MANDATORY, READ_ONLY)
VALUES (NEXTVAL('SEQ_DEPARTMENT_ID'), 'Finance', FALSE, FALSE);

INSERT INTO DEPARTMENT (ID, NAME, MANDATORY, READ_ONLY)
VALUES (NEXTVAL('SEQ_DEPARTMENT_ID'), 'Peoples', FALSE, FALSE);

INSERT INTO DEPARTMENT (ID, NAME, MANDATORY, READ_ONLY)
VALUES (NEXTVAL('SEQ_DEPARTMENT_ID'), 'Development', FALSE, FALSE);

INSERT INTO EMPLOYEE (ID, NAME_FIRST, NAME_LAST)
VALUES (NEXTVAL('SEQ_EMPLOYEE_ID'), 'Nishant', 'Kumar');

INSERT INTO EMPLOYEE (ID, NAME_FIRST, NAME_LAST)
VALUES (NEXTVAL('SEQ_EMPLOYEE_ID'), 'Rohit', 'Sharma');

INSERT INTO EMPLOYEE (ID, NAME_FIRST, NAME_LAST)
VALUES (NEXTVAL('SEQ_EMPLOYEE_ID'), 'Manu', 'Bhaker');

INSERT INTO EMPLOYEE (ID, NAME_FIRST, NAME_LAST)
VALUES (NEXTVAL('SEQ_EMPLOYEE_ID'), 'Lakshaya', 'Sen');